version: 2
updates:
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@google-cloud/firestore"
    versions:
    - 4.8.1
    - 4.9.1
    - 4.9.2
    - 4.9.3
    - 4.9.4
    - 4.9.6
    - 4.9.7
    - 4.9.8
    - 4.9.9
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
    - 6.0.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: firebase-admin
    versions:
    - 9.4.2
    - 9.5.0
  - dependency-name: firebase-functions
    versions:
    - 3.13.1
